version: '3.7'

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - db:db
    networks:
      mynet:
        ipv4_address: 10.2.0.2
    volumes:
      - ./TorneioFacil/www:/var/www/html/

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mynet:
        ipv4_address: 10.2.0.3

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    ports:
      - 800:8080
    networks:
      mynet:
        ipv4_address: 10.2.0.4

volumes:
  mysql-data:


    # chcon -Rt svirt_sandbox_file_t TorneioFacil/